Ca 62 forgot password
metlapp/community-app pull request #11
Opened 2020-10-27 19:11 UTC by JaycobDuffel

2020-10-28 18:41 UTC, katiemcgoff commented on screens/VerifyEmailScreen.js
> +        onSubmit={async (values) => {
Let's move this function out of inline and up to a const, since there will be more to it once we actually hook up the API.

2020-10-28 18:43 UTC, katiemcgoff commented on screens/ResetPasswordScreen.js
> +        onSubmit={async (values) => {
Same for this function - it would be better above the return() statement, but still within the component.

2020-10-28 18:52 UTC, katiemcgoff commented on screens/VerifyEmailScreen.js
> +export default function RegisterPassword({ navigation }) {
This is a function component but I believe we're going with class-based components. Also, wrong name?

2020-10-28 18:54 UTC, katiemcgoff commented on screens/VerifyEmailScreen.js
> +export default function RegisterPassword({ navigation }) {
Nevermind - but still same comment re. the name of the component.

2020-10-28 18:54 UTC, katiemcgoff requested changes
changes requested

2020-10-29 16:51 UTC, DawsonDease approved these changes

2020-10-29 19:47 UTC, katiemcgoff approved these changes

2020-10-29 19:49 UTC, merged