CA-153-Display-Fixed-Text
metlapp/community-app pull request #29
Opened 2020-12-05 00:01 UTC by JaycobDuffel

2020-12-05 01:54 UTC, katiemcgoff commented
This looks good. However let's hold off until the homepage style changes are in, and then you can incorporate this into those changes. For this, it will mainly be subbing out the card component for our custom ContentCard component.

2020-12-09 18:38 UTC, DawsonDease approved these changes

2020-12-10 21:17 UTC, katiemcgoff requested changes
- test HomeScreen component and FixedTest component separately
- use common theme styling, with paper components and defaultTheme constants, as much as possible
- see if right-aligning the author name gives you what you want rather than left position.

2020-12-10 22:47 UTC, katiemcgoff approved these changes

2020-12-11 03:05 UTC, merged