Ca 170 answer surveys
metlapp/community-app pull request #37
Opened 2020-12-21 21:24 UTC by DawsonDease

2020-12-21 21:44 UTC, JaycobDuffel requested changes

2020-12-21 21:44 UTC, JaycobDuffel commented on components/Survey.js
> +import PropTypes from "prop-types";
Prop types aren't implemented

2020-12-21 21:44 UTC, JaycobDuffel commented on screens/SurveyScreen.js
> +
remove unused imports

2020-12-21 21:46 UTC, katiemcgoff approved these changes

2020-12-21 21:47 UTC, katiemcgoff commented on config/config.js
> +
This commented-out line shouldn't be checked in.

2020-12-21 21:48 UTC, katiemcgoff commented on screens/NotificationScreen.js
> +import { HOST_WITH_PORT } from "../environment";
HOST_WITH_PORT isn't used.

2020-12-21 21:48 UTC, katiemcgoff commented on screens/QuestionScreen.js
> +import { HOST_WITH_PORT } from "../environment";
HOST_WITH_PORT isn't used.

2020-12-21 21:49 UTC, katiemcgoff requested changes
Unused imports (plus what Jaycob found), otherwise good.

2020-12-22 18:03 UTC, JaycobDuffel approved these changes

2020-12-22 18:12 UTC, katiemcgoff approved these changes

2020-12-22 20:01 UTC, merged